version: "3"
services:
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - .:/var/lib/my_data
    ports:
      - 27017:27017
  postgres-demo:
    image: postgres
    container_name: postgres-demo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=myapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/my_data
    restart: always
  redis:
    image: redis
    container_name: redis
    ports:
      -  6379:6379
    volumes:
      - .:/var/lib/my_data
    restart: always
  django:
    image: 
      django-docker:0.0.1
    build: .
    tty: true
    ports:
      -  8000:8000
    depends_on:
      - mongo
      - postgres-demo
      - redis
    entrypoint: bash


      

          
